In [1]:
import os
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [30]:
Dataset1 = '/content/drive/MyDrive/Colab Notebooks/dataset/News_With_StockCode.csv'
Dataset2 = '/content/drive/MyDrive/Colab Notebooks/dataset/kakao.csv'

In [147]:
import pandas as pd
df = pd.read_csv(Dataset1)
del df['content']
df.head()

                  date                                title     code
0  2020-02-25 10:08:05                세계 경제에 이미 '팬데믹 공포' 고조  a066570
1  2020-02-26 09:05:26           코스피, 또 2% 급락 출발…2,060대로 후퇴  a066570
2  2020-02-26 09:17:35       코스피, 또 급락 출발…외인 매도에 2,060대로 후퇴  a066570
3  2020-02-26 09:36:23  코스피, 또 급락 출발…외국인 매도에 2,060대로 후퇴(종합)  a000660
4  2020-02-26 16:53:28       카카오뱅크, 코로나19 확산에 본사 직원 한시 재택근무  a035720

In [148]:
df['label'] = 1 # 테스트용 라벨링링

In [149]:
df.head()

                  date                                title     code  label
0  2020-02-25 10:08:05                세계 경제에 이미 '팬데믹 공포' 고조  a066570      1
1  2020-02-26 09:05:26           코스피, 또 2% 급락 출발…2,060대로 후퇴  a066570      1
2  2020-02-26 09:17:35       코스피, 또 급락 출발…외인 매도에 2,060대로 후퇴  a066570      1
3  2020-02-26 09:36:23  코스피, 또 급락 출발…외국인 매도에 2,060대로 후퇴(종합)  a000660      1
4  2020-02-26 16:53:28       카카오뱅크, 코로나19 확산에 본사 직원 한시 재택근무  a035720      1

In [150]:
df2 = pd.read_csv(Dataset2)

del df2['volume']
del df2['ma14']
del df2['ma70']
del df2['ma140']
del df2['rsi14']
del df2['rsi70']
del df2['rsi140']
del df2['rsi196']
del df2['bol_upper']
del df2['bol_down']
del df2['dollar']
del df2['nasdaq100']

df2.head()

# 가독이 쉽도록 date와 close 값만 보이게

                  date    close
0  2020-02-25 09:00:00  36430.0
1  2020-02-25 09:30:00  36932.0
2  2020-02-25 10:00:00  37032.0
3  2020-02-25 10:30:00  37032.0
4  2020-02-25 11:00:00  37133.0

In [143]:
df['date'] = pd.to_datetime(df['date'])  # 형태를 바꿔줌

In [144]:
df2['date'] = pd.to_datetime(df2['date'])

In [146]:
# if 문을 활용해서 연도 -> 월 -> 일 -> 시간으로 검색
# 만약 같은 값이 나온다면 세부적인 시간을 통해 xx시 00분에 라벨링 할지 xx시 30분에 라벨링할지 정함
# 모든 데이터를 쓸 수 없기 때문에 기사가 나온 시점과 제일 비슷한 시점의 주식 데이터에 라벨링 하고자 했음 -> 실패 
# ex) 기사가 10시 27분에 나왔다면 10시 30분 주식 데이터에 감성표현을 라벨링 하고자 함 

for i in range(len(df['date'])): 
  for j in range(len(df['date'])):
    if(df['date'].dt.year[i] == df2['date'].dt.year[j]):
      if(df['date'].dt.month[i] == df2['date'].dt.month[j]):
        if(df['date'].dt.date[i] == df2['date'].dt.date[j]):
          if(df['date'].dt.hour[i] == df2['date'].dt.hour[j]):
            print(df['date'].dt.date[i])
            print(df2['date'].dt.date[j])

KeyError: ignored